<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>a123114e-5143-4d9f-a00c-f595c75a62af</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.EntityFrameworkCore" Version="13.5.2-preview.1.26421.6" />
    <PackageReference Include="Aspire.Hosting.Kafka" Version="13.5.4" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.5.4" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="13.5.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Inbox.LoadTest\Inbox.LoadTest.csproj" />
    <ProjectReference Include="..\Web\Web.csproj" />
  </ItemGroup>

</Project>
